services:
  mongodb:
    image: mongo:8
    container_name: sentinelnet-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - sentinelnet-mongo-data:/data/db

volumes:
  sentinelnet-mongo-data: